version: "3"

services:
  frontend:
    restart: unless-stopped
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: classquiz_frontend
    depends_on:
      - redis
      - api
    environment:
      REDIS_URL: "redis://redis:6379/0?decode_responses=True"
      API_URL: "http://api:80"

  api:
    build: &build_cfg
      context: .
      dockerfile: Dockerfile
    container_name: classquiz_api
    restart: &restart unless-stopped
    depends_on: &depends
      - db
      - redis
    environment: &env_vars
      DB_URL: "postgresql://classquiz:classquiz_db_password@db:5432/classquiz"
      REDIS: "redis://redis:6379/0?decode_responses=True"
      SECRET_KEY: "SecretKeyUniquePourSessionClassquiz"
      MAX_WORKERS: "1"
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
      MEILISEARCH_URL: "http://meilisearch:7700"
      ROOT_ADDRESS: "http://192.168.1.253:8000"
      MAIL_PORT: "25"
      MAIL_ADDRESS: "noreply@example.com"
      MAIL_PASSWORD: ""
      MAIL_USERNAME: ""
      MAIL_SERVER: "127.0.0.1"
      SKIP_EMAIL_VERIFICATION: "True"
      STORAGE_BACKEND: "local"
      STORAGE_PATH: "/app/data"
    volumes:
      - /volume1/docker/classquiz/uploads:/app/data

  redis:
    image: valkey/valkey:alpine
    container_name: classquiz_redis
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "valkey-cli", "ping"]

  db:
    image: postgres:14-alpine
    container_name: classquiz_db
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U classquiz"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: "classquiz"
      POSTGRES_PASSWORD: "classquiz_db_password"
      POSTGRES_DB: "classquiz"
    volumes:
      - /volume1/docker/classquiz/postgres_data:/var/lib/postgresql/data

  proxy:
    image: ghcr.io/mawoka-myblock/classquiz-caddy:master
    container_name: classquiz_proxy
    restart: unless-stopped
    depends_on:
      - frontend
      - api
    ports:
      - "8000:8080"

  meilisearch:
    image: getmeili/meilisearch:v1.1
    container_name: classquiz_search
    restart: unless-stopped
    environment:
      MEILI_NO_ANALYTICS: "true"
    volumes:
      - /volume1/docker/classquiz/meili_data:/data.ms

  worker:
    build: *build_cfg
    container_name: classquiz_worker
    environment: *env_vars
    depends_on: *depends
    restart: *restart
    command: arq classquiz.worker.WorkerSettings
    volumes:
      - /volume1/docker/classquiz/uploads:/app/data
